config/routes.rb
Discoverible::Application.routes.draw do
  # API
  get 'facets', to: 'facets#index'
  post 'collections/update'
  get 'results', to: 'results#index'
  get 'collections/typeahead', to: 'collections#typeahead'
  
  # Pages
  root to: 'home#index'
  get 'signin', to: 'home#create_collection'
  get '/youtube/:channel_id', to: 'collections#show'
  get '/youtube/:channel_id/edit', to: 'collections#edit'
  get 'contact', to: 'contact#index'
  
  # API
  get 'settings/authorize_upload'
  get 'settings/process_image'
  post 'settings/update'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/create'
  
  post 'add_facet', to: 'facets#create'
  post 'facets/update'
  post 'delete_facet', to: 'facets#destroy'
  post 'reorder', to: 'facets#reorder'
  post 'rename_value', to: 'values#update'
  post 'delete_value', to: 'values#destroy'
  post 'resources/edit', to: 'resources#edit'
  post 'resources/edit_all', to: 'resources#edit_all'
  post 'resources', to: 'resources#create'
  delete 'resources/:id', to: 'resources#destroy'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    owner = User.find(:first, :conditions => ["lower(username) = ?", params[:username].downcase])
    if owner
      @owner = { username: owner.username }
      @user_data = {username: current_user.username, isOwner: @is_owner} if current_user
      @collections = owner.collections
      @humanized_type = {
        'Video' => 'video',
        'YoutubeCollection' => 'YouTube collection'
      }
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end
  
  def show
    owner = User.find(:first, :conditions => ["lower(username) = ?", params[:username].downcase])
    if owner
      @is_owner = (owner == current_user)
      @owner = { username: owner.username, image_url: owner.image_url }
      @user_data = {username: current_user.username, isOwner: @is_owner} if current_user
      @collections_data = owner.collections.map do |collection|
        facet_list = collection.facets.select('name').map { |f| f.name }.join(', ')
        {
          url: '/' + owner.username + '/' + collection.slug,
          title: collection.title,
          description: collection.description,
          image_url: collection.image_url,
          # resources_description: "<strong>#{collection.resources.count}</strong>" + ' item'.pluralize(collection.resources.count),
          resources_description: '<strong>Items: </strong>' + collection.resources.count.to_s,
          facets_description: collection.facets.any? ? '<strong>Facets: </strong>' + view_context.sanitize(facet_list) : '<strong>Facets: </strong><span class="muted">None</span>'
        }
      end
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end
  
  def new
    redirect_to '/' + current_user.username if current_user
  end

  def create
    @user = User.new(email: params[:email], password: params[:password], username: params[:username])
    if @user.save
      session[:user_id] = @user.id
      render :json => @user
    else
      render :json => @user.errors.messages
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_collection_snippet_template.html.erb
<script type="text/html" id="youtube-collection-snippet-template">
  <div class="youtube-collection-snippet">
    <img class="youtube-collection-image" data-bind="attr: { src: image_url }">
    <div data-bind="html: resources_description"></div>
    <div data-bind="html: facets_description"></div>
  </div>
</script>

app/views/users/_create_collection.html.erb
<!--<img id="profile-image" width="150" height="150" data-bind="attr: { src: '/assets/' + user.user().username + '.jpg' }">-->
<!--<img id="profile-image" width="150" height="150" src="http://s3.amazonaws.com/di-images/pivan">-->
<!--<h4 style="margin:10px 0;" data-bind="text: user.user().username">HuskyStarcraft</h4>-->

<h5>Create a new collection</h5>
    
<form class="form-inline">
  <small class="settings-label" style="float:left;">Name</small>
  <div class="column-right"><input type="text"></div>
</form>
<button class="btn btn-small btn-primary">Create</button>

<h5 id="profile" style="margin-top:20px;">Profile</h5>

<div style="margin-bottom:20px;">
  <small class="settings-label" style="float:left;">Image</small>
  <input type="file" name="file" id="file-input">
  <div class="column-right">
    
    <div class="choose-button-container">
      <button type="button" class="btn" id="choose-button" style="margin-bottom:5px;">Choose image</button>
      <span id="filename">No image selected</span>
    </div>
    <div class="format-error"><small class="text-error">The image must be a JPG, PNG or GIF file.</small></div>
    <div class="size-error"><small class="text-error">The image must be less than 2 MB.</small></div>
    <div style="margin-top:5px;">
      <button type="button" class="btn btn-primary" id="upload-button">Upload</button>
      <img id="loading" src="assets/ajax-loader.gif">
    </div>
    <div style="margin-top:5px;"><small class="muted">Maximum file size: 2MB</small></div>
    <div><small class="muted">For best results, choose a square image.</small></div>
  </div>
</div>

<form class="form-inline">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
  <small class="settings-label" style="float:left;">Heading</small>
  <div class="column-right">
    <input type="text">
  </div>
</form>

app/views/users/_header.html.erb
<div class="navbar">
  <div class="container">
  
    <a href="/" class="logo"></a>
  
    <div class="content clearfix">
  
      <!--
      <div class="pull-left" style="margin-top:5px;">
        <div class="input-container">
          <i class="icon-search muted"></i>
          <input class="input-small" type="text" id="search" autocomplete="off" <%= 'disabled' if defined? disable_search %>>
        </div>
      </div>
      -->
      
      <!-- ko if: user.user -->
        <div class="pull-right">
          <small><a href="/sessions/destroy" style="line-height:40px;">Log out</a></small>
        </div>
      <!-- /ko -->
   
      <% if false %>
      <div class="nav pull-right">
        <!-- ko ifnot: user.user -->
          <small><a href="#" style="line-height:40px;" data-bind="click: user.showSignIn">Log in</a></small>
        <!-- /ko -->
        <!-- ko if: user.user -->
          <small id="name" data-toggle="dropdown">
            <a href="#">
              <span data-bind="text: user.user().username"></span>
              <i class="icon-caret-down"></i>
            </a>
          </small>
          <ul class="dropdown-menu pull-right" style="margin-top:-8px;">
            <li><a data-bind="attr: { href: '/' + user.user().username }">Your page</a></li>
            <li><a href="/settings">Settings</a></li>
            <li><a href="/sessions/destroy">Log out</a></li>
          </ul>
        <!-- /ko -->
      </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render partial: "shared/header", locals: {narrow: true} %>

<div class="container">
  <div class="content">

    <h3><%= @owner[:username] %></h3>
    <h5 style="margin-bottom:20px;">Collections</h5>

    <% @collections.each do |collection| %>
      <% collection_url = url_for controller: 'collections', action: 'index', username: @owner[:username], collection: collection.slug %>
      <% facets_string = collection.facets.pluck('name').join(', ') %>
      <% count = 'Empty' %>
      <% count = pluralize(collection.resources.count, @humanized_type[collection.resources[0].type]) if collection.resources.any? %>
      <div class="clearfix" style="margin-bottom:20px;">
      
        <a href="<%= collection_url %>"><img class="collection-thumb pull-left" width="60" height="60" src="<%= collection.image_url %>" style="margin-right:10px;"></a>
        
        <div><strong><a href="<%= collection_url %>"><%= collection.title %></strong></a></div>
        
        <div><small class="muted"><%= count %></small></div>
        
        <% collection.facets.each do |facet| %>
          <small><%= facet.name %></small>
          <small class="muted"> (<%= facet.values.count %>)</small><%= ',' unless collection.facets.last == facet %>
        <% end %>
        
      </div>
    <% end %>
      
  </div>
</div>

<div class="di-modal-backdrop"></div>
<%= render "shared/sign_in_modal" %>

<script>
  <% if @user_data %>
    di.userData = <%= raw @user_data.to_json %>;
  <% end %>
  ko.applyBindings(di);
  di.user.init();
</script>

app/views/users/new.html.erb
<%= render partial: "shared/header" %>

<div class="container">
<div class="content">

  <form class="form-inline form-signup" data-bind="submit: user.signUp">
    <h3>Sign up</h3>
    
    <p>
      <small>Email</small>
      <input type="text" class="input-block-level" id="email-input" data-bind="value: user.email">
      <small class="text-error" style="display:none;">Email is not valid.</small>
      <small class="text-error" style="display:none;">Email has already been taken.</small>
    </p>
    
    <p>
      <small>Password</small>
      <input type="password" class="input-block-level" id="password-input" data-bind="value: user.password">
      <small class="text-error" style="display:none;">Password must be 6 characters minimum.</small>
    </p>
    
    <p>
      <small>Username</small>
      <input type="text" class="input-block-level" id="username-input" data-bind="value: user.username">
      <small class="muted" data-bind="text: 'http://discoverible.com/' + user.username()" ></small>
      <br>
      <small class="text-error" style="display:none;">Username can't be blank.</small>
      <small class="text-error" style="display:none;">Username has already been taken.</small>
    </p>
    
    <div>
      <button class="btn btn-primary" type="submit">Sign up</button>
    </div>
  </form>

</div>
</div>

<div class="di-modal-backdrop"></div>
<%= render "collections/sign_in" %>

<script>
  $(function () {
    ko.applyBindings(di);
    di.user.init();
  });
</script>

app/views/users/show.html.erb
<%= render partial: "header" %>

<div class="container">

  <!--<img class="pull-right" src="http://placehold.it/160x600">-->

  <div class="sidebar" data-bind="with: sidebar">
    <img id="collection-image" width="150" height="150" src="<%= @owner[:image_url] %>">
  </div>

  <div class="content clearfix">
  <div style="float:left;width:100%;">
  
    <h3 style="line-height:25px;"><%= @owner[:username] %></h3>
    <div style="margin-bottom:10px;">
      <small><strong><%= @collections_data.length %></strong> Collections</small>
    </div>
    
    <!--
    <div style="margin-bottom:10px;">
      <% if @is_owner %>
        <small><a href="/settings">Settings</a></small>
      <% end %>
    </div>
    -->
    
    <div id="waiting"></div>
    <!--
    <div class="status-bar">
      <small><strong><%= @collections_data.length %></strong> Collections</small>
    </div>
    -->
    
    <ol class="result-list" data-bind="foreach: users.listItems">
      <li class="result" data-bind="click: $root.users.selectListItem, css: { 'selected-resource': $data === $root.users.selectedListItem() }">
        <div class="result-inner clearfix">

          <div class="resource-title"><a data-bind="attr: { href: url }, text: title"></a></div>
          
          <div class="resource-actions">
            <!-- ko ifnot: $data === $root.users.selectedListItem() -->
              <a href="#" class="watch-action">Expand</a>
            <!-- /ko -->
            <!-- ko if: $data === $root.users.selectedListItem() -->
              <a href="#" class="watch-action">Collapse</a>
            <!-- /ko -->
          </div>
          
          <!-- ko if: $data === $root.users.selectedListItem() -->
            <!-- ko template: { name: 'youtube-collection-snippet-template', data: $data } --><!-- /ko -->
          <!-- /ko -->
          
        </div>
      </li>
    </ol>
    
  </div>
  </div>
  
</div>

<%= render "collection_snippet_template" %>
<div class="di-modal-backdrop"></div>
<%= render "shared/sign_in_modal" %>

<script>
  di.collectionData = <%= raw @collections_data.to_json %>;
  <% if @user_data %>
    di.userData = <%= raw @user_data.to_json %>;
  <% end %>
  ko.applyBindings(di);
  di.users.init();
  di.user.init();
</script>